fix(apps): Tweaks to improve the Firefox tab line color in focal
pop-os/gtk-theme pull request #513
Opened 2021-04-20 21:21 UTC by isantop

This unfortunately affects all of Firefox, so we also darken the color so enable
it to have somewhat acceptable contrast. It is confined to Firefox though.

2021-04-23 14:02 UTC, jackpot51 approved these changes

2021-04-28 15:52 UTC, jacobgkau requested changes
Tested on a Focal machine with https://github.com/pop-os/gtk-theme/pull/514. 

In addition to fixing the tab color, this also pulls in a number of other changes from the Groovy branch. While some of these (like Nautilus's path bar) are fine, at least one is causing a problem with search results in Activities:

![Screenshot from 2021-04-28 09-49-39](https://user-images.githubusercontent.com/7199422/116434129-5ccb5900-a807-11eb-91e9-5bd74f357080.png)

This is what it should look like, for comparison:

![Screenshot from 2021-04-28 09-50-12](https://user-images.githubusercontent.com/7199422/116434147-648afd80-a807-11eb-9269-80aa68f3f3c5.png)

2021-04-28 16:58 UTC, jackpot51 approved these changes

2021-04-28 21:53 UTC, isantop commented
> Tested on a Focal machine with #514.
> 
> In addition to fixing the tab color, this also pulls in a number of other changes from the Groovy branch. While some of these (like Nautilus's path bar) are fine, at least one is causing a problem with search results in Activities:
> 
> ![Screenshot from 2021-04-28 09-49-39](https://user-images.githubusercontent.com/7199422/116434129-5ccb5900-a807-11eb-91e9-5bd74f357080.png)
> 
> This is what it should look like, for comparison:
> 
> ![Screenshot from 2021-04-28 09-50-12](https://user-images.githubusercontent.com/7199422/116434147-648afd80-a807-11eb-9269-80aa68f3f3c5.png)

I see, This will need to be reimplemented from scratch for Focal.

2021-04-28 21:53 UTC, closed without merging